version: '3'
services:
  db:
    platform: linux/x86_64
    image: library/mysql:8.0.23
    container_name: starlucks-mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
  redis:
    container_name: starlucks-redis
    image: redis:7.0.10
    ports:
      - "16379:6379"