server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/starlucks?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root