name: gyh-every-push

on:
  pull_request:
    branches: [ feature ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test, Lint, Build
        uses: actions/setup-java@v1
        with:
          java-version: 17