name: PR Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2

      - name: Super-Linter
      - uses: github/super-linter@v4.10.0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17